apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    jenkins.io/job-full-name: generated-pipelines/TSI/fraud-service/fraud-service-cd
  description: This is a service called fraud-service
  name: fraud-service
  tags:
  - golang-service
  - business-reliability-impact
  - experience-impact
  - offline-impact
  - non-critical
  - high
spec:
  lifecycle: production
  owner: platform-integrity
  type: service
