apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    jenkins.io/job-full-name: generated-pipelines/wallet/wallet-service/wallet-service-webserver-cd
  description: This is a service called wallet-service
  name: wallet-service
  tags:
  - java-service
  - experience-impact
spec:
  lifecycle: production
  owner: wallet
  type: service
