apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    jenkins.io/job-full-name: generated-pipelines/mobility-be-customer-engagement/package-service/package-service-cd
  description: This is a service called package-service
  name: package-service
  tags:
  - java-service
  - business-reliability-impact-1
spec:
  lifecycle: production
  owner: promotions
  type: service
