apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    jenkins.io/job-full-name: generated-pipelines/captain/captain-app-event-service/captain-app-event-service-cd
  description: This is a service called captain-app-event-service
  name: captain-app-event-service
  tags:
  - java-service
  - offline-impact-3
spec:
  lifecycle: production
  owner: mobility-be-experience-infra
  type: service
