apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    jenkins.io/job-full-name: generated-pipelines/customer-payments/cpay-nginx-proxy/cpay-nginx-proxy-cd
  description: This is a service called cpay-nginx-proxy
  name: cpay-nginx-proxy
  tags:
  - java-service
  - experience-impact
spec:
  lifecycle: production
  owner: customer-payments
  type: service
