apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    jenkins.io/job-full-name: generated-pipelines/mobility-be-express/espresso/espresso-cd
  description: This is a service called espresso
  name: espresso
  tags:
  - java-service
  - non-critical
spec:
  lifecycle: production
  owner: mobility-be-express-team
  type: service
