apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    jenkins.io/job-full-name: generated-pipelines/mobility-be-engagement/captain-super-zone-service/captain-super-zone-service-cd
  description: This is a service called captain-super-zone-service
  name: captain-super-zone-service
  tags:
  - java-service
  - high
spec:
  lifecycle: production
  owner: mobility-be-engagement-and-acquisition
  type: service
