apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    jenkins.io/job-full-name: generated-pipelines/mobility-be-engagement-and-acquisition/supply-registry-service/supply-registry-service-cd
  description: This is a service called supply-registry-service
  name: supply-registry-service
  tags:
  - java-service
  - experience-impact
spec:
  lifecycle: production
  owner: mobility-be-engagement-and-acquisition
  type: service
