apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    jenkins.io/job-full-name: generated-pipelines/falcon/facial-recognition-service/facial-recognition-service-qa-cd
  description: This is a service called facial-recognition-service
  name: facial-recognition-service
  tags:
  - java-service
  - business-reliability-impact
spec:
  lifecycle: production
  owner: mountain-peak
  type: service
