apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    jenkins.io/job-full-name: generated-pipelines/careempay-integration/careempay-integration-adaptor-ding/careempay-integration-adaptor-ding-cd
  description: This is a service called careempay-integration-adaptor-ding
  name: careempay-integration-adaptor-ding
  tags:
  - golang-service
  - business-reliability-impact
spec:
  lifecycle: production
  owner: careempay-integration
  type: service
